export const IMAGE_GAL = [
    {src:'/photoGal1.jpg', alt:'image1'},
    {src:'/photogal2.jpg', alt:'image2'},
    {src:'/photogal3.jpg', alt:'image3'},
    {src:'/photogal4.jpg', alt:'image4'},
    {src:'/photogal7.jpg', alt:'image7'},
    {src:'/homepage3.jpg', alt:'image11'},
    {src:'/homepage5.jpg', alt:'image12'},
    {src:'/homepage8.jpg', alt:'image13'},
    {src:'/Herpetafauna1.jpg', alt:'image14'},
    {src:'/makandawa rain forest.jpg', alt:'image15'},
    {src:'/floratour1.jpg', alt:'image16'},
    {src:'/birding tour2.jpg', alt:'image17'},
    {src:'/165564216.jpg', alt:'image18'},
]

export const IMAGE_GAL_PAGE = [
    {src:'/photoGal1.jpg', alt:'image1'},
    {src:'/photogal2.jpg', alt:'image2'},
    {src:'/photogal3.jpg', alt:'image3'},
    {src:'/photogal4.jpg', alt:'image4'},
    {src:'/photogal7.jpg', alt:'image7'},
    {src:'/sigiriya sanctuary.jpg', alt:'image8'},
    {src:'/mammal tour1.jpg', alt:'image9'},
    {src:'/mammal tour2.jpg', alt:'image10'},
    {src:'/homepage3.jpg', alt:'image11'},
    {src:'/homepage5.jpg', alt:'image12'},
    {src:'/homepage8.jpg', alt:'image13'},
    {src:'/Herpetafauna1.jpg', alt:'image14'},
    {src:'/makandawa rain forest.jpg', alt:'image15'},
    {src:'/floratour1.jpg', alt:'image16'},
    {src:'/birding tour2.jpg', alt:'image17'},
    {src:'/165564216.jpg', alt:'image18'},
]